---
baseurl: ""
title: "Site Title"
languageCode: "en-us"
theme: "hello-abyss"
paginate: 10
enableGitInfo: false
copyright: '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
enableRobotsTXT: true
enableEmoji: true

params:
  dateform: "Jan 2, 2006"
  dateformShort: "Jan 2"
  dateformNum: "2006-01-02"
  dateformNumTime: "2006-01-02 15:04 -0700"

  # Subtitle for Page (HTML) Title
  # subtitle: "Subtitle"

  # Subtitle for home
  homeSubtitle: "System Administration // DevOps"

  readOtherPosts: "More posts"
  disableReadOtherPosts: false

  # Enable sharing buttons, if you like
  enableSharingButtons: true

  # Metadata mostly used in document's head
  description: "Thoughts from a System Administrator turned DevOps Enthusiast"
  keywords: "homepage, blog, devops, system administration, cloud, aws, azure, ansible, terraform, portfolio"
  images: [""]

  # Canonical baseURL (with no slash) for rel="canonical"
  canonicalURL: "https://abyss.dev"

  # Default theme "light" or "dark"
  defaultTheme: "dark"

  # Override the View Source
  footerSource: "<a href=\"https://github.com/abyss/abyss.dev\">View Source</a>"

  # Social icons
  social:
    main:
      - name: twitter
        url: https://twitter.com/AbyssVI
      - name: github
        url: https://github.com/abyss
      - name: discord
        url: https://discord.abyss.dev/

  logo:
    logoCursorColor: "#aaa"
    logoHomeLink: "/"

taxonomies:
  tag: "tags"
  series: "series"

# menu:
#   main:
#     - name: "Posts"
#       identifier: "posts"
#       url: "/posts"

#     - name: "About"
#       identifier: "about"
#       url: "/about"

permalinks:
  posts: "/posts/:slug/"
