baseurl: "https://cwr.io"
title: "Craig Reeder"

params:
  author:
    name: "Craig Reeder"
  defaultTheme: "light"

  social:
    - name: github
      url: https://github.com/abyss
    - name: linkedin
      url: https://www.linkedin.com/in/craig-reeder/
